import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const exercises = [
  // SQUATS & LEGS
  {
    name: "Squat",
    nameEn: "Squat",
    nameFr: "Squat",
    nameIt: "Squat",
    nameEs: "Sentadilla",
    nameNl: "Squat",
    description: "Squat complet avec barre",
    muscleGroups: ["legs", "glutes", "quadriceps"],
  },
  {
    name: "Front Squat",
    nameEn: "Front Squat",
    nameFr: "Squat avant",
    nameIt: "Squat frontale",
    nameEs: "Sentadilla frontal",
    nameNl: "Front squat",
    description: "Squat avec barre devant",
    muscleGroups: ["legs", "quadriceps", "core"],
  },
  {
    name: "Back Squat",
    nameEn: "Back Squat",
    nameFr: "Squat arrière",
    nameIt: "Squat posteriore",
    nameEs: "Sentadilla trasera",
    nameNl: "Back squat",
    description: "Squat classique avec barre dans le dos",
    muscleGroups: ["legs", "glutes", "quadriceps"],
  },
  {
    name: "Bulgarian Split Squat",
    nameEn: "Bulgarian Split Squat",
    nameFr: "Fente bulgare",
    nameIt: "Affondo bulgaro",
    nameEs: "Zancada búlgara",
    nameNl: "Bulgaarse split squat",
    description: "Fente avec pied arrière surélevé",
    muscleGroups: ["legs", "glutes", "quadriceps"],
  },
  {
    name: "Goblet Squat",
    nameEn: "Goblet Squat",
    nameFr: "Squat gobelet",
    nameIt: "Squat con kettlebell",
    nameEs: "Sentadilla con pesa",
    nameNl: "Goblet squat",
    description: "Squat avec haltère tenu devant",
    muscleGroups: ["legs", "glutes", "quadriceps", "core"],
  },
  {
    name: "Hack Squat",
    nameEn: "Hack Squat",
    nameFr: "Hack squat",
    nameIt: "Hack squat",
    nameEs: "Hack squat",
    nameNl: "Hack squat",
    description: "Squat à la machine hack",
    muscleGroups: ["legs", "quadriceps"],
  },
  {
    name: "Leg Press",
    nameEn: "Leg Press",
    nameFr: "Presse à cuisses",
    nameIt: "Pressa per gambe",
    nameEs: "Prensa de piernas",
    nameNl: "Leg press",
    description: "Presse à cuisses",
    muscleGroups: ["legs", "quadriceps", "glutes"],
  },
  {
    name: "Lunges",
    nameEn: "Lunges",
    nameFr: "Fentes",
    nameIt: "Affondi",
    nameEs: "Zancadas",
    nameNl: "Lunges",
    description: "Fentes alternées",
    muscleGroups: ["legs", "glutes", "quadriceps"],
  },
  {
    name: "Walking Lunges",
    nameEn: "Walking Lunges",
    nameFr: "Fentes marchées",
    nameIt: "Affondi camminati",
    nameEs: "Zancadas caminando",
    nameNl: "Wandelende lunges",
    description: "Fentes en marchant",
    muscleGroups: ["legs", "glutes", "quadriceps"],
  },
  {
    name: "Leg Extension",
    nameEn: "Leg Extension",
    nameFr: "Extension de jambes",
    nameIt: "Estensione gambe",
    nameEs: "Extensión de piernas",
    nameNl: "Been extensie",
    description: "Extension de jambes à la machine",
    muscleGroups: ["legs", "quadriceps"],
  },
  {
    name: "Leg Curl",
    nameEn: "Leg Curl",
    nameFr: "Curl de jambes",
    nameIt: "Curl gambe",
    nameEs: "Curl de piernas",
    nameNl: "Been curl",
    description: "Curl de jambes",
    muscleGroups: ["legs", "hamstrings"],
  },
  {
    name: "Romanian Deadlift",
    nameEn: "Romanian Deadlift",
    nameFr: "Soulevé de terre roumain",
    nameIt: "Stacco rumeno",
    nameEs: "Peso muerto rumano",
    nameNl: "Roemeense deadlift",
    description: "Soulevé de terre roumain",
    muscleGroups: ["back", "hamstrings", "glutes"],
  },
  {
    name: "Stiff Leg Deadlift",
    nameEn: "Stiff Leg Deadlift",
    nameFr: "Soulevé de terre jambes tendues",
    nameIt: "Stacco a gambe tese",
    nameEs: "Peso muerto piernas rectas",
    nameNl: "Stijve deadlift",
    description: "Soulevé de terre jambes tendues",
    muscleGroups: ["back", "hamstrings"],
  },
  {
    name: "Calf Raise",
    nameEn: "Calf Raise",
    nameFr: "Mollets debout",
    nameIt: "Sollevamenti polpacci",
    nameEs: "Elevación de gemelos",
    nameNl: "Kuitheffing",
    description: "Mollets debout",
    muscleGroups: ["legs", "calves"],
  },
  {
    name: "Seated Calf Raise",
    nameEn: "Seated Calf Raise",
    nameFr: "Mollets assis",
    nameIt: "Sollevamenti polpacci seduti",
    nameEs: "Elevación de gemelos sentado",
    nameNl: "Zittende kuitheffing",
    description: "Mollets assis",
    muscleGroups: ["legs", "calves"],
  },

  // CHEST EXERCISES
  {
    name: "Bench Press",
    nameEn: "Bench Press",
    nameFr: "Développé couché",
    nameIt: "Panca piana",
    nameEs: "Press de banca",
    nameNl: "Bankdrukken",
    description: "Développé couché",
    muscleGroups: ["chest", "triceps", "shoulders"],
  },
  {
    name: "Incline Bench Press",
    nameEn: "Incline Bench Press",
    nameFr: "Développé incliné",
    nameIt: "Panca inclinata",
    nameEs: "Press inclinado",
    nameNl: "Schuine bankdrukken",
    description: "Développé incliné",
    muscleGroups: ["chest", "shoulders", "triceps"],
  },
  {
    name: "Decline Bench Press",
    nameEn: "Decline Bench Press",
    nameFr: "Développé décliné",
    nameIt: "Panca declinata",
    nameEs: "Press declinado",
    nameNl: "Decline bankdrukken",
    description: "Développé décliné",
    muscleGroups: ["chest", "triceps"],
  },
  {
    name: "Dumbbell Bench Press",
    nameEn: "Dumbbell Bench Press",
    nameFr: "Développé couché haltères",
    nameIt: "Panca con manubri",
    nameEs: "Press con mancuernas",
    nameNl: "Halters bankdrukken",
    description: "Développé couché avec haltères",
    muscleGroups: ["chest", "triceps", "shoulders"],
  },
  {
    name: "Incline Dumbbell Press",
    nameEn: "Incline Dumbbell Press",
    nameFr: "Développé incliné haltères",
    nameIt: "Panca inclinata con manubri",
    nameEs: "Press inclinado con mancuernas",
    nameNl: "Schuine halter bankdrukken",
    description: "Développé incliné avec haltères",
    muscleGroups: ["chest", "shoulders", "triceps"],
  },
  {
    name: "Decline Dumbbell Press",
    nameEn: "Decline Dumbbell Press",
    nameFr: "Développé décliné haltères",
    nameIt: "Panca declinata con manubri",
    nameEs: "Press declinado con mancuernas",
    nameNl: "Decline halter bankdrukken",
    description: "Développé décliné avec haltères",
    muscleGroups: ["chest", "triceps"],
  },
  {
    name: "Chest Fly",
    nameEn: "Chest Fly",
    nameFr: "Écarté couché",
    nameIt: "Croci panca",
    nameEs: "Aperturas",
    nameNl: "Vliegen",
    description: "Écarté couché",
    muscleGroups: ["chest"],
  },
  {
    name: "Incline Chest Fly",
    nameEn: "Incline Chest Fly",
    nameFr: "Écarté incliné",
    nameIt: "Croci panca inclinata",
    nameEs: "Aperturas inclinadas",
    nameNl: "Schuine vliegen",
    description: "Écarté incliné",
    muscleGroups: ["chest"],
  },
  {
    name: "Decline Chest Fly",
    nameEn: "Decline Chest Fly",
    nameFr: "Écarté décliné",
    nameIt: "Croci panca declinata",
    nameEs: "Aperturas declinadas",
    nameNl: "Decline vliegen",
    description: "Écarté décliné",
    muscleGroups: ["chest"],
  },
  {
    name: "Push-ups",
    nameEn: "Push-ups",
    nameFr: "Pompes",
    nameIt: "Flessioni",
    nameEs: "Flexiones",
    nameNl: "Push-ups",
    description: "Pompes",
    muscleGroups: ["chest", "triceps", "shoulders"],
  },
  {
    name: "Incline Push-ups",
    nameEn: "Incline Push-ups",
    nameFr: "Pompes inclinées",
    nameIt: "Flessioni inclinate",
    nameEs: "Flexiones inclinadas",
    nameNl: "Schuine push-ups",
    description: "Pompes inclinées",
    muscleGroups: ["chest", "triceps", "shoulders"],
  },
  {
    name: "Decline Push-ups",
    nameEn: "Decline Push-ups",
    nameFr: "Pompes déclinées",
    nameIt: "Flessioni declinate",
    nameEs: "Flexiones declinadas",
    nameNl: "Decline push-ups",
    description: "Pompes déclinées",
    muscleGroups: ["chest", "triceps", "shoulders"],
  },
  {
    name: "Dips",
    nameEn: "Dips",
    nameFr: "Pompes aux barres parallèles",
    nameIt: "Dip",
    nameEs: "Fondos",
    nameNl: "Dips",
    description: "Pompes aux barres parallèles",
    muscleGroups: ["triceps", "chest", "shoulders"],
  },
  {
    name: "Chest Dips",
    nameEn: "Chest Dips",
    nameFr: "Dips poitrine",
    nameIt: "Dip petto",
    nameEs: "Fondos de pecho",
    nameNl: "Borst dips",
    description: "Dips orientés poitrine",
    muscleGroups: ["chest", "triceps", "shoulders"],
  },

  // BACK EXERCISES
  {
    name: "Deadlift",
    nameEn: "Deadlift",
    nameFr: "Soulevé de terre",
    nameIt: "Stacco",
    nameEs: "Peso muerto",
    nameNl: "Deadlift",
    description: "Soulevé de terre",
    muscleGroups: ["back", "legs", "glutes", "hamstrings"],
  },
  {
    name: "Barbell Row",
    nameEn: "Barbell Row",
    nameFr: "Tirage barre",
    nameIt: "Remata con bilanciere",
    nameEs: "Remo con barra",
    nameNl: "Barbell row",
    description: "Tirage barre",
    muscleGroups: ["back", "biceps"],
  },
  {
    name: "Bent Over Row",
    nameEn: "Bent Over Row",
    nameFr: "Rowing penché",
    nameIt: "Remata piegato",
    nameEs: "Remo inclinado",
    nameNl: "Bent over row",
    description: "Rowing penché",
    muscleGroups: ["back", "biceps"],
  },
  {
    name: "T-Bar Row",
    nameEn: "T-Bar Row",
    nameFr: "Rowing T-bar",
    nameIt: "Remata T-bar",
    nameEs: "Remo T-bar",
    nameNl: "T-bar row",
    description: "Rowing T-bar",
    muscleGroups: ["back", "biceps"],
  },
  {
    name: "Pull-ups",
    nameEn: "Pull-ups",
    nameFr: "Tractions",
    nameIt: "Trazioni",
    nameEs: "Dominadas",
    nameNl: "Pull-ups",
    description: "Tractions",
    muscleGroups: ["back", "biceps"],
  },
  {
    name: "Chin-ups",
    nameEn: "Chin-ups",
    nameFr: "Tractions supination",
    nameIt: "Trazioni supinate",
    nameEs: "Dominadas supinas",
    nameNl: "Chin-ups",
    description: "Tractions en supination",
    muscleGroups: ["back", "biceps"],
  },
  {
    name: "Wide Grip Pull-ups",
    nameEn: "Wide Grip Pull-ups",
    nameFr: "Tractions prise large",
    nameIt: "Trazioni presa larga",
    nameEs: "Dominadas agarre ancho",
    nameNl: "Wijde pull-ups",
    description: "Tractions prise large",
    muscleGroups: ["back", "biceps"],
  },
  {
    name: "Close Grip Pull-ups",
    nameEn: "Close Grip Pull-ups",
    nameFr: "Tractions prise serrée",
    nameIt: "Trazioni presa stretta",
    nameEs: "Dominadas agarre cerrado",
    nameNl: "Smalle pull-ups",
    description: "Tractions prise serrée",
    muscleGroups: ["back", "biceps"],
  },
  {
    name: "Lat Pulldown",
    nameEn: "Lat Pulldown",
    nameFr: "Tirage vertical",
    nameIt: "Lat machine",
    nameEs: "Jalón al pecho",
    nameNl: "Lat pulldown",
    description: "Tirage vertical",
    muscleGroups: ["back", "biceps"],
  },
  {
    name: "Wide Grip Lat Pulldown",
    nameEn: "Wide Grip Lat Pulldown",
    nameFr: "Tirage vertical prise large",
    nameIt: "Lat machine presa larga",
    nameEs: "Jalón agarre ancho",
    nameNl: "Wijde lat pulldown",
    description: "Tirage vertical prise large",
    muscleGroups: ["back", "biceps"],
  },
  {
    name: "Close Grip Lat Pulldown",
    nameEn: "Close Grip Lat Pulldown",
    nameFr: "Tirage vertical prise serrée",
    nameIt: "Lat machine presa stretta",
    nameEs: "Jalón agarre cerrado",
    nameNl: "Smalle lat pulldown",
    description: "Tirage vertical prise serrée",
    muscleGroups: ["back", "biceps"],
  },
  {
    name: "Seated Cable Row",
    nameEn: "Seated Cable Row",
    nameFr: "Tirage horizontal",
    nameIt: "Remata cavi",
    nameEs: "Remo con polea",
    nameNl: "Zittende cable row",
    description: "Tirage horizontal assis",
    muscleGroups: ["back", "biceps"],
  },
  {
    name: "One Arm Dumbbell Row",
    nameEn: "One Arm Dumbbell Row",
    nameFr: "Rowing unilatéral",
    nameIt: "Remata manubrio singolo",
    nameEs: "Remo con mancuerna",
    nameNl: "Eenarmige halter row",
    description: "Rowing unilatéral avec haltère",
    muscleGroups: ["back", "biceps"],
  },
  {
    name: "Cable Row",
    nameEn: "Cable Row",
    nameFr: "Rowing à la poulie",
    nameIt: "Remata cavi",
    nameEs: "Remo con polea",
    nameNl: "Cable row",
    description: "Rowing à la poulie",
    muscleGroups: ["back", "biceps"],
  },
  {
    name: "Face Pull",
    nameEn: "Face Pull",
    nameFr: "Tirage visage",
    nameIt: "Face pull",
    nameEs: "Jalón facial",
    nameNl: "Face pull",
    description: "Tirage visage",
    muscleGroups: ["back", "shoulders"],
  },
  {
    name: "Shrugs",
    nameEn: "Shrugs",
    nameFr: "Haussements d'épaules",
    nameIt: "Scrollate",
    nameEs: "Encogimientos",
    nameNl: "Shrugs",
    description: "Haussements d'épaules",
    muscleGroups: ["back", "traps"],
  },

  // SHOULDER EXERCISES
  {
    name: "Overhead Press",
    nameEn: "Overhead Press",
    nameFr: "Développé militaire",
    nameIt: "Lento avanti",
    nameEs: "Press militar",
    nameNl: "Overhead press",
    description: "Développé militaire",
    muscleGroups: ["shoulders", "triceps"],
  },
  {
    name: "Shoulder Press",
    nameEn: "Shoulder Press",
    nameFr: "Développé épaules",
    nameIt: "Press spalle",
    nameEs: "Press de hombros",
    nameNl: "Schouder press",
    description: "Développé épaules",
    muscleGroups: ["shoulders", "triceps"],
  },
  {
    name: "Dumbbell Shoulder Press",
    nameEn: "Dumbbell Shoulder Press",
    nameFr: "Développé épaules haltères",
    nameIt: "Press spalle manubri",
    nameEs: "Press de hombros con mancuernas",
    nameNl: "Halter schouder press",
    description: "Développé épaules avec haltères",
    muscleGroups: ["shoulders", "triceps"],
  },
  {
    name: "Arnold Press",
    nameEn: "Arnold Press",
    nameFr: "Développé Arnold",
    nameIt: "Press Arnold",
    nameEs: "Press Arnold",
    nameNl: "Arnold press",
    description: "Développé Arnold",
    muscleGroups: ["shoulders", "triceps"],
  },
  {
    name: "Lateral Raise",
    nameEn: "Lateral Raise",
    nameFr: "Élévations latérales",
    nameIt: "Alzate laterali",
    nameEs: "Elevaciones laterales",
    nameNl: "Zijwaartse heffing",
    description: "Élévations latérales",
    muscleGroups: ["shoulders"],
  },
  {
    name: "Front Raise",
    nameEn: "Front Raise",
    nameFr: "Élévations frontales",
    nameIt: "Alzate frontali",
    nameEs: "Elevaciones frontales",
    nameNl: "Voorwaartse heffing",
    description: "Élévations frontales",
    muscleGroups: ["shoulders"],
  },
  {
    name: "Rear Delt Fly",
    nameEn: "Rear Delt Fly",
    nameFr: "Élévations postérieures",
    nameIt: "Alzate posteriori",
    nameEs: "Elevaciones posteriores",
    nameNl: "Achterwaartse vliegen",
    description: "Élévations postérieures",
    muscleGroups: ["shoulders"],
  },
  {
    name: "Upright Row",
    nameEn: "Upright Row",
    nameFr: "Rowing debout",
    nameIt: "Remata verticale",
    nameEs: "Remo vertical",
    nameNl: "Upright row",
    description: "Rowing debout",
    muscleGroups: ["shoulders", "traps"],
  },
  {
    name: "Pike Push-ups",
    nameEn: "Pike Push-ups",
    nameFr: "Pompes pike",
    nameIt: "Flessioni pike",
    nameEs: "Flexiones pike",
    nameNl: "Pike push-ups",
    description: "Pompes pike",
    muscleGroups: ["shoulders", "triceps"],
  },

  // BICEPS EXERCISES
  {
    name: "Bicep Curl",
    nameEn: "Bicep Curl",
    nameFr: "Curl biceps",
    nameIt: "Curl bicipiti",
    nameEs: "Curl de bíceps",
    nameNl: "Bicep curl",
    description: "Curl biceps",
    muscleGroups: ["biceps"],
  },
  {
    name: "Hammer Curl",
    nameEn: "Hammer Curl",
    nameFr: "Curl marteau",
    nameIt: "Curl martello",
    nameEs: "Curl martillo",
    nameNl: "Hammer curl",
    description: "Curl marteau",
    muscleGroups: ["biceps", "forearms"],
  },
  {
    name: "Preacher Curl",
    nameEn: "Preacher Curl",
    nameFr: "Curl pupitre",
    nameIt: "Curl panca Scott",
    nameEs: "Curl predicador",
    nameNl: "Preacher curl",
    description: "Curl pupitre",
    muscleGroups: ["biceps"],
  },
  {
    name: "Concentration Curl",
    nameEn: "Concentration Curl",
    nameFr: "Curl concentration",
    nameIt: "Curl concentrato",
    nameEs: "Curl concentrado",
    nameNl: "Concentratie curl",
    description: "Curl concentration",
    muscleGroups: ["biceps"],
  },
  {
    name: "Cable Curl",
    nameEn: "Cable Curl",
    nameFr: "Curl à la poulie",
    nameIt: "Curl cavi",
    nameEs: "Curl con polea",
    nameNl: "Cable curl",
    description: "Curl à la poulie",
    muscleGroups: ["biceps"],
  },
  {
    name: "21s",
    nameEn: "21s",
    nameFr: "21s",
    nameIt: "21s",
    nameEs: "21s",
    nameNl: "21s",
    description: "Curl 21 répétitions",
    muscleGroups: ["biceps"],
  },
  {
    name: "Spider Curl",
    nameEn: "Spider Curl",
    nameFr: "Curl araignée",
    nameIt: "Curl ragno",
    nameEs: "Curl araña",
    nameNl: "Spider curl",
    description: "Curl araignée",
    muscleGroups: ["biceps"],
  },

  // TRICEPS EXERCISES
  {
    name: "Tricep Extension",
    nameEn: "Tricep Extension",
    nameFr: "Extension triceps",
    nameIt: "Estensione tricipiti",
    nameEs: "Extensión de tríceps",
    nameNl: "Tricep extensie",
    description: "Extension triceps",
    muscleGroups: ["triceps"],
  },
  {
    name: "Overhead Tricep Extension",
    nameEn: "Overhead Tricep Extension",
    nameFr: "Extension triceps au-dessus",
    nameIt: "Estensione tricipiti sopra",
    nameEs: "Extensión de tríceps por encima",
    nameNl: "Overhead tricep extensie",
    description: "Extension triceps au-dessus de la tête",
    muscleGroups: ["triceps"],
  },
  {
    name: "Close Grip Bench Press",
    nameEn: "Close Grip Bench Press",
    nameFr: "Développé couché prise serrée",
    nameIt: "Panca presa stretta",
    nameEs: "Press agarre cerrado",
    nameNl: "Smalle bankdrukken",
    description: "Développé couché prise serrée",
    muscleGroups: ["triceps", "chest"],
  },
  {
    name: "Tricep Kickback",
    nameEn: "Tricep Kickback",
    nameFr: "Extension triceps couché",
    nameIt: "Kickback tricipiti",
    nameEs: "Patada de tríceps",
    nameNl: "Tricep kickback",
    description: "Extension triceps couché",
    muscleGroups: ["triceps"],
  },
  {
    name: "Tricep Rope Extension",
    nameEn: "Tricep Rope Extension",
    nameFr: "Extension triceps corde",
    nameIt: "Estensione tricipiti corda",
    nameEs: "Extensión de tríceps con cuerda",
    nameNl: "Tricep touw extensie",
    description: "Extension triceps avec corde",
    muscleGroups: ["triceps"],
  },
  {
    name: "Diamond Push-ups",
    nameEn: "Diamond Push-ups",
    nameFr: "Pompes diamant",
    nameIt: "Flessioni diamante",
    nameEs: "Flexiones diamante",
    nameNl: "Diamant push-ups",
    description: "Pompes diamant",
    muscleGroups: ["triceps", "chest"],
  },

  // CORE EXERCISES
  {
    name: "Plank",
    nameEn: "Plank",
    nameFr: "Planche",
    nameIt: "Plank",
    nameEs: "Plancha",
    nameNl: "Plank",
    description: "Planche",
    muscleGroups: ["core"],
  },
  {
    name: "Side Plank",
    nameEn: "Side Plank",
    nameFr: "Planche latérale",
    nameIt: "Plank laterale",
    nameEs: "Plancha lateral",
    nameNl: "Zijwaartse plank",
    description: "Planche latérale",
    muscleGroups: ["core"],
  },
  {
    name: "Russian Twist",
    nameEn: "Russian Twist",
    nameFr: "Russian twist",
    nameIt: "Russian twist",
    nameEs: "Giro ruso",
    nameNl: "Russische twist",
    description: "Russian twist",
    muscleGroups: ["core"],
  },
  {
    name: "Crunches",
    nameEn: "Crunches",
    nameFr: "Crunchs",
    nameIt: "Crunch",
    nameEs: "Abdominales",
    nameNl: "Crunches",
    description: "Crunchs",
    muscleGroups: ["core"],
  },
  {
    name: "Leg Raises",
    nameEn: "Leg Raises",
    nameFr: "Relevés de jambes",
    nameIt: "Sollevamenti gambe",
    nameEs: "Elevaciones de piernas",
    nameNl: "Beenheffingen",
    description: "Relevés de jambes",
    muscleGroups: ["core"],
  },
  {
    name: "Hanging Leg Raises",
    nameEn: "Hanging Leg Raises",
    nameFr: "Relevés de jambes suspendu",
    nameIt: "Sollevamenti gambe sospeso",
    nameEs: "Elevaciones de piernas colgado",
    nameNl: "Hangende beenheffingen",
    description: "Relevés de jambes suspendu",
    muscleGroups: ["core"],
  },
  {
    name: "Mountain Climbers",
    nameEn: "Mountain Climbers",
    nameFr: "Mountain climbers",
    nameIt: "Scalatori",
    nameEs: "Escaladores",
    nameNl: "Bergbeklimmers",
    description: "Mountain climbers",
    muscleGroups: ["core"],
  },
  {
    name: "Dead Bug",
    nameEn: "Dead Bug",
    nameFr: "Dead bug",
    nameIt: "Dead bug",
    nameEs: "Bicho muerto",
    nameNl: "Dode bug",
    description: "Dead bug",
    muscleGroups: ["core"],
  },
  {
    name: "Ab Wheel Rollout",
    nameEn: "Ab Wheel Rollout",
    nameFr: "Roue abdominale",
    nameIt: "Ruota addominale",
    nameEs: "Rueda abdominal",
    nameNl: "Buikwiel",
    description: "Roue abdominale",
    muscleGroups: ["core"],
  },

  // CALISTHENICS & ADVANCED BODYWEIGHT
  {
    name: "Muscle-up",
    nameEn: "Muscle-up",
    nameFr: "Muscle-up",
    nameIt: "Muscle-up",
    nameEs: "Muscle-up",
    nameNl: "Muscle-up",
    description: "Muscle-up aux barres",
    muscleGroups: ["back", "biceps", "triceps", "shoulders"],
  },
  {
    name: "Handstand Push-ups",
    nameEn: "Handstand Push-ups",
    nameFr: "Pompes en équilibre",
    nameIt: "Flessioni verticali",
    nameEs: "Flexiones verticales",
    nameNl: "Handstand push-ups",
    description: "Pompes en équilibre sur les mains",
    muscleGroups: ["shoulders", "triceps", "core"],
  },
  {
    name: "Wall Handstand",
    nameEn: "Wall Handstand",
    nameFr: "Équilibre contre le mur",
    nameIt: "Verticale al muro",
    nameEs: "Parada de manos en pared",
    nameNl: "Handstand tegen muur",
    description: "Équilibre contre le mur",
    muscleGroups: ["shoulders", "core"],
  },
  {
    name: "L-sit",
    nameEn: "L-sit",
    nameFr: "L-sit",
    nameIt: "L-sit",
    nameEs: "L-sit",
    nameNl: "L-sit",
    description: "Assis en L",
    muscleGroups: ["core"],
  },
  {
    name: "Human Flag",
    nameEn: "Human Flag",
    nameFr: "Drapeau humain",
    nameIt: "Bandiera umana",
    nameEs: "Bandera humana",
    nameNl: "Menselijke vlag",
    description: "Drapeau humain",
    muscleGroups: ["core", "shoulders", "back"],
  },
  {
    name: "Planche",
    nameEn: "Planche",
    nameFr: "Planche",
    nameIt: "Planche",
    nameEs: "Plancha",
    nameNl: "Planche",
    description: "Planche (calisthenics)",
    muscleGroups: ["shoulders", "core"],
  },
  {
    name: "Front Lever",
    nameEn: "Front Lever",
    nameFr: "Lever avant",
    nameIt: "Front lever",
    nameEs: "Palanca frontal",
    nameNl: "Front lever",
    description: "Lever avant",
    muscleGroups: ["back", "core"],
  },
  {
    name: "Back Lever",
    nameEn: "Back Lever",
    nameFr: "Lever arrière",
    nameIt: "Back lever",
    nameEs: "Palanca trasera",
    nameNl: "Back lever",
    description: "Lever arrière",
    muscleGroups: ["back", "core"],
  },
  {
    name: "Pistol Squat",
    nameEn: "Pistol Squat",
    nameFr: "Squat pistol",
    nameIt: "Squat pistol",
    nameEs: "Sentadilla pistol",
    nameNl: "Pistol squat",
    description: "Squat sur une jambe",
    muscleGroups: ["legs", "glutes", "quadriceps"],
  },
  {
    name: "Burpees",
    nameEn: "Burpees",
    nameFr: "Burpees",
    nameIt: "Burpees",
    nameEs: "Burpees",
    nameNl: "Burpees",
    description: "Burpees",
    muscleGroups: ["legs", "chest", "shoulders", "core"],
  },
  {
    name: "Jumping Jacks",
    nameEn: "Jumping Jacks",
    nameFr: "Sauts écartés",
    nameIt: "Salti a stella",
    nameEs: "Saltos de tijera",
    nameNl: "Jumping jacks",
    description: "Sauts écartés",
    muscleGroups: ["legs", "shoulders"],
  },
  {
    name: "Box Jumps",
    nameEn: "Box Jumps",
    nameFr: "Sauts sur box",
    nameIt: "Salti sul box",
    nameEs: "Saltos al cajón",
    nameNl: "Box jumps",
    description: "Sauts sur box",
    muscleGroups: ["legs", "glutes"],
  },

  // CARDIO EXERCISES
  {
    name: "Rowing Machine",
    nameEn: "Rowing Machine",
    nameFr: "Rameur",
    nameIt: "Vogatore",
    nameEs: "Remo",
    nameNl: "Roeimachine",
    description: "Rameur",
    muscleGroups: ["back", "legs", "shoulders", "cardio"],
  },
  {
    name: "Stair Climbing",
    nameEn: "Stair Climbing",
    nameFr: "Montée d'escaliers",
    nameIt: "Scalata scale",
    nameEs: "Subida de escaleras",
    nameNl: "Traplopen",
    description: "Montée d'escaliers",
    muscleGroups: ["legs", "glutes", "cardio"],
  },
  {
    name: "StairMaster",
    nameEn: "StairMaster",
    nameFr: "Stepper",
    nameIt: "Stepper",
    nameEs: "Escaladora",
    nameNl: "StairMaster",
    description: "Stepper / escalier mécanique",
    muscleGroups: ["legs", "glutes", "cardio"],
  },
  {
    name: "Running",
    nameEn: "Running",
    nameFr: "Course à pied",
    nameIt: "Corsa",
    nameEs: "Correr",
    nameNl: "Hardlopen",
    description: "Course à pied",
    muscleGroups: ["legs", "cardio"],
  },
  {
    name: "Treadmill",
    nameEn: "Treadmill",
    nameFr: "Tapis de course",
    nameIt: "Tapis roulante",
    nameEs: "Cinta de correr",
    nameNl: "Loopband",
    description: "Tapis de course",
    muscleGroups: ["legs", "cardio"],
  },
  {
    name: "Cycling",
    nameEn: "Cycling",
    nameFr: "Vélo",
    nameIt: "Ciclismo",
    nameEs: "Ciclismo",
    nameNl: "Fietsen",
    description: "Vélo",
    muscleGroups: ["legs", "cardio"],
  },
  {
    name: "Stationary Bike",
    nameEn: "Stationary Bike",
    nameFr: "Vélo stationnaire",
    nameIt: "Bicicletta stazionaria",
    nameEs: "Bicicleta estática",
    nameNl: "Hometrainer",
    description: "Vélo stationnaire",
    muscleGroups: ["legs", "cardio"],
  },
  {
    name: "Elliptical",
    nameEn: "Elliptical",
    nameFr: "Elliptique",
    nameIt: "Ellittica",
    nameEs: "Elíptica",
    nameNl: "Crosstrainer",
    description: "Elliptique",
    muscleGroups: ["legs", "arms", "cardio"],
  },
  {
    name: "Jump Rope",
    nameEn: "Jump Rope",
    nameFr: "Corde à sauter",
    nameIt: "Corda per saltare",
    nameEs: "Saltar la cuerda",
    nameNl: "Touwtjespringen",
    description: "Corde à sauter",
    muscleGroups: ["legs", "shoulders", "cardio"],
  },
  {
    name: "Rowing",
    nameEn: "Rowing",
    nameFr: "Aviron",
    nameIt: "Canottaggio",
    nameEs: "Remo",
    nameNl: "Roeien",
    description: "Aviron (sport)",
    muscleGroups: ["back", "legs", "shoulders", "cardio"],
  },
  {
    name: "Swimming",
    nameEn: "Swimming",
    nameFr: "Natation",
    nameIt: "Nuoto",
    nameEs: "Natación",
    nameNl: "Zwemmen",
    description: "Natation",
    muscleGroups: ["back", "shoulders", "legs", "cardio"],
  },
  {
    name: "High Intensity Interval Training",
    nameEn: "High Intensity Interval Training",
    nameFr: "HIIT",
    nameIt: "HIIT",
    nameEs: "HIIT",
    nameNl: "HIIT",
    description: "Entraînement par intervalles à haute intensité",
    muscleGroups: ["cardio", "full body"],
  },
  {
    name: "Sprint",
    nameEn: "Sprint",
    nameFr: "Sprint",
    nameIt: "Sprint",
    nameEs: "Sprint",
    nameNl: "Sprint",
    description: "Sprint",
    muscleGroups: ["legs", "cardio"],
  },
  {
    name: "Walking",
    nameEn: "Walking",
    nameFr: "Marche",
    nameIt: "Camminata",
    nameEs: "Caminar",
    nameNl: "Wandelen",
    description: "Marche",
    muscleGroups: ["legs", "cardio"],
  },
  {
    name: "Power Walking",
    nameEn: "Power Walking",
    nameFr: "Marche rapide",
    nameIt: "Camminata veloce",
    nameEs: "Caminata rápida",
    nameNl: "Power walking",
    description: "Marche rapide",
    muscleGroups: ["legs", "cardio"],
  },
  {
    name: "Hiking",
    nameEn: "Hiking",
    nameFr: "Randonnée",
    nameIt: "Escursionismo",
    nameEs: "Senderismo",
    nameNl: "Wandelen",
    description: "Randonnée",
    muscleGroups: ["legs", "cardio"],
  },
  {
    name: "Assault Bike",
    nameEn: "Assault Bike",
    nameFr: "Vélo assault",
    nameIt: "Bicicletta assault",
    nameEs: "Bicicleta assault",
    nameNl: "Assault bike",
    description: "Vélo assault / air bike",
    muscleGroups: ["legs", "arms", "cardio"],
  },
  {
    name: "SkiErg",
    nameEn: "SkiErg",
    nameFr: "SkiErg",
    nameIt: "SkiErg",
    nameEs: "SkiErg",
    nameNl: "SkiErg",
    description: "SkiErg / simulateur de ski",
    muscleGroups: ["back", "shoulders", "legs", "cardio"],
  },
  {
    name: "BikeErg",
    nameEn: "BikeErg",
    nameFr: "BikeErg",
    nameIt: "BikeErg",
    nameEs: "BikeErg",
    nameNl: "BikeErg",
    description: "BikeErg / vélo ergomètre",
    muscleGroups: ["legs", "cardio"],
  },
  {
    name: "Rowing Ergometer",
    nameEn: "Rowing Ergometer",
    nameFr: "Ergomètre rameur",
    nameIt: "Ergometro vogatore",
    nameEs: "Ergómetro de remo",
    nameNl: "Roeiergometer",
    description: "Ergomètre rameur",
    muscleGroups: ["back", "legs", "shoulders", "cardio"],
  },
  {
    name: "Step Mill",
    nameEn: "Step Mill",
    nameFr: "Escalier mécanique",
    nameIt: "Scala mobile",
    nameEs: "Escalera mecánica",
    nameNl: "Traploopmachine",
    description: "Escalier mécanique",
    muscleGroups: ["legs", "glutes", "cardio"],
  },
  {
    name: "Cross Trainer",
    nameEn: "Cross Trainer",
    nameFr: "Cross trainer",
    nameIt: "Cross trainer",
    nameEs: "Entrenador cruzado",
    nameNl: "Crosstrainer",
    description: "Cross trainer",
    muscleGroups: ["legs", "arms", "cardio"],
  },
];

async function main() {
  console.log("🌱 Seeding exercises...");

  for (const exercise of exercises) {
    await prisma.exercise.upsert({
      where: { name: exercise.name },
      update: {},
      create: exercise,
    });
  }

  console.log(`✅ Seeded ${exercises.length} exercises`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
